name: Install, Download, 和 Compress

on: [push]  # 或者其他触发条件

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: python install.py
     
    - name: Download files
      run: python gh.py
      working-directory: ./build

    - name: Compress files
      run: tar -czvf downloaded-files.tar.gz -C ./path/to/downloaded/files .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compressed-files
        path: downloaded-files.tar.gz
