name: Install, Download, 和 Compress

on: [push]  # 或者其他触发条件

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: python install.py

    - name: Download files
      run: python gh.py
      working-directory: ./build

    - name: Wait for files to settle
      run: sleep 10  # 等待10秒，确保所有文件下载完成

    - name: Sync files 和 Compress
      run: |
        # 使用 rsync 同步文件到一个临时目录
        rsync -avz --progress ./build/ /tmp/build-sync/
        # 切换到临时目录并压缩文件
        cd /tmp/build-sync/
        tar -czvf /tmp/downloaded-files.tar.gz .
        # 将压缩文件移回原来的位置
        mv /tmp/downloaded-files.tar.gz $GITHUB_WORKSPACE

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compressed-files
        path: downloaded-files.tar.gz
