name: Install, Download, 和 Compress

on: [push]  # 或者其他触发条件

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: python install.py

    - name: Download files
      run: python gh.py
      working-directory: ./build

    - name: Compress files
      run: tar -czvf ./build/downloaded-files.tar.gz -C ./build/ .

    - name: Check file existence
      run: ls -l ./build/downloaded-files.tar.gz

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compressed-files
        path: ./build/downloaded-files.tar.gz
        if-no-files-found: warn
        include-hidden-files: false
